// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContactUpdate struct {
	Clock                           uint64                   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	EnsName                         string                   `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	ProfileImage                    string                   `protobuf:"bytes,3,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	SentContactRequestSignature     *ContactRequestSignature `protobuf:"bytes,14,opt,name=sent_contact_request_signature,json=sentContactRequestSignature,proto3" json:"sent_contact_request_signature,omitempty"`
	ReceivedContactRequestSignature *ContactRequestSignature `protobuf:"bytes,15,opt,name=received_contact_request_signature,json=receivedContactRequestSignature,proto3" json:"received_contact_request_signature,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}                 `json:"-"`
	XXX_unrecognized                []byte                   `json:"-"`
	XXX_sizecache                   int32                    `json:"-"`
}

func (m *ContactUpdate) Reset()         { *m = ContactUpdate{} }
func (m *ContactUpdate) String() string { return proto.CompactTextString(m) }
func (*ContactUpdate) ProtoMessage()    {}
func (*ContactUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0}
}

func (m *ContactUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactUpdate.Unmarshal(m, b)
}
func (m *ContactUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactUpdate.Marshal(b, m, deterministic)
}
func (m *ContactUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactUpdate.Merge(m, src)
}
func (m *ContactUpdate) XXX_Size() int {
	return xxx_messageInfo_ContactUpdate.Size(m)
}
func (m *ContactUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ContactUpdate proto.InternalMessageInfo

func (m *ContactUpdate) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *ContactUpdate) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *ContactUpdate) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *ContactUpdate) GetSentContactRequestSignature() *ContactRequestSignature {
	if m != nil {
		return m.SentContactRequestSignature
	}
	return nil
}

func (m *ContactUpdate) GetReceivedContactRequestSignature() *ContactRequestSignature {
	if m != nil {
		return m.ReceivedContactRequestSignature
	}
	return nil
}

func init() {
	proto.RegisterType((*ContactUpdate)(nil), "protobuf.ContactUpdate")
}

func init() {
	proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15)
}

var fileDescriptor_a5036fff2565fb15 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0x3f, 0x4f, 0xc3, 0x30,
	0x14, 0xc4, 0x95, 0xf2, 0xaf, 0xb8, 0x04, 0x24, 0x8b, 0x21, 0x80, 0x04, 0xa1, 0x2c, 0x99, 0x82,
	0x04, 0x23, 0x1b, 0x4c, 0x2c, 0x0c, 0x41, 0x2c, 0x2c, 0xd6, 0xab, 0x7b, 0x09, 0x11, 0x8d, 0x1d,
	0xec, 0x17, 0xbe, 0x1d, 0xdf, 0x0d, 0x35, 0x89, 0xc7, 0x20, 0x26, 0xfb, 0xdd, 0xfd, 0x74, 0x77,
	0x22, 0xd6, 0xd6, 0x30, 0x69, 0xce, 0x5b, 0x67, 0xd9, 0xca, 0x79, 0xff, 0xac, 0xba, 0xf2, 0x5c,
	0xea, 0x0f, 0x62, 0xd5, 0xc0, 0x7b, 0xaa, 0x30, 0xb8, 0xcb, 0x9f, 0x99, 0x88, 0x9f, 0x06, 0xfe,
	0xad, 0x5d, 0x13, 0x43, 0x9e, 0x8a, 0x3d, 0xbd, 0xb1, 0xfa, 0x33, 0x89, 0xd2, 0x28, 0xdb, 0x2d,
	0x86, 0x43, 0x9e, 0x89, 0x39, 0x8c, 0x57, 0x86, 0x1a, 0x24, 0xb3, 0x34, 0xca, 0x0e, 0x8b, 0x03,
	0x18, 0xff, 0x42, 0x0d, 0xe4, 0x8d, 0x88, 0x5b, 0x67, 0xcb, 0x7a, 0x03, 0x55, 0x37, 0x54, 0x21,
	0xd9, 0xe9, 0xfd, 0xa3, 0x51, 0x7c, 0xde, 0x6a, 0xb2, 0x14, 0x97, 0x1e, 0x86, 0xd5, 0xb8, 0x4d,
	0x39, 0x7c, 0x75, 0xf0, 0xac, 0x7c, 0x5d, 0x19, 0xe2, 0xce, 0x21, 0x39, 0x4e, 0xa3, 0x6c, 0x71,
	0x77, 0x9d, 0x87, 0xb9, 0xf9, 0x38, 0xab, 0x18, 0xc8, 0xd7, 0x00, 0x16, 0x17, 0xdb, 0xa0, 0x09,
	0x53, 0x1a, 0xb1, 0x74, 0xd0, 0xa8, 0xbf, 0xb1, 0xfe, 0xa3, 0xeb, 0xe4, 0xbf, 0x5d, 0x57, 0x21,
	0x6c, 0x02, 0x78, 0x8c, 0xdf, 0x17, 0xf9, 0xed, 0x43, 0xc8, 0x59, 0xed, 0xf7, 0xbf, 0xfb, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0x62, 0x02, 0x80, 0x84, 0x01, 0x00, 0x00,
}
